bitbag_sylius_mailchimp_plugin_newsletter_subscribe:
    path: /newsletter/subscribe
    methods: ["POST", "PATCH"]
    defaults:
        _controller: bitbag_sylius_mailchimp_plugin.controller.newsletter:subscribeAction

bitbag_sylius_mailchimp_plugin_webhook:
    path: /mailchimp/webhook
    methods: ["POST", "GET"]
    defaults:
        _controller: bitbag_sylius_mailchimp_plugin.controller.mailchimp:webhookAction
