services:
    bitbag_sylius_mailchimp_plugin.validator.email_validator:
        class: BitBag\SyliusMailChimpPlugin\Validator\NewsletterValidator
        public: true
        arguments:
            - "@validator"

    bitbag_sylius_mailchimp_plugin.validator.webhook_validator:
        class: BitBag\SyliusMailChimpPlugin\Validator\WebhookValidator
        public: true
        arguments:
            - "@validator"
            - "%mailchimp.list_id%"
            - "%mailchimp.webhook_secret%"

    bitbag_sylius_mailchimp_plugin.controller.newsletter:
        class: BitBag\SyliusMailChimpPlugin\Controller\NewsletterController
        public: true
        arguments:
            - "@bitbag_sylius_mailchimp_plugin.validator.email_validator"
            - "@translator"
            - "@bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler"
            - "@security.csrf.token_manager"

    bitbag_sylius_mailchimp_plugin.controller.mailchimp:
        class: BitBag\SyliusMailChimpPlugin\Controller\MailchimpController
        public: true
        arguments:
            - "@bitbag_sylius_mailchimp_plugin.validator.webhook_validator"
            - "@bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler"
            - "@translator"

    bitbag_sylius_mailchimp_plugin.drewm.mailchimp:
        class: DrewM\MailChimp\MailChimp
        public: true
        arguments:
            - "%mailchimp.api_key%"

    bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler:
        class: BitBag\SyliusMailChimpPlugin\Handler\NewsletterSubscriptionHandler
        public: true
        arguments:
            - "@sylius.repository.customer"
            - "@sylius.factory.customer"
            - "@sylius.manager.customer"
            - "@bitbag_sylius_mailchimp_plugin.drewm.mailchimp"
            - "%mailchimp.list_id%"

    bitbag_sylius_mailchimp_plugin.validator.unique_newsletter_email_validator:
        class: BitBag\SyliusMailChimpPlugin\Validator\Constraints\UniqueNewsletterEmailValidator
        public: true
        arguments:
            - "@sylius.repository.customer"
        tags:
            - { name: "validator.constraint_validator" }

    bitbag_sylius_mailchimp_plugin.event_listener.customer_listener:
        class: BitBag\SyliusMailChimpPlugin\EventListener\CustomerNewsletterListener
        public: true
        arguments:
            - "@bitbag_sylius_mailchimp_plugin.handler.newsletter_subscription_handler"
            - "@fos_oauth_server.entity_manager"
        tags:
            - { name: "kernel.event_listener", event: "sylius.customer.post_register", method: customerCreateEvent }
            - { name: "kernel.event_listener", event: "sylius.customer.pre_update", method: customerPreUpdateEvent }
            - { name: "kernel.event_listener", event: "sylius.customer.post_update", method: customerPostUpdateEvent }
